Doxygen: DocHtmlPicture Class Reference
DocHtmlPicture Class Reference
Node Html picture.
#include <docnode.h>
Public Member Functions
DocHtmlPicture (DocParser *parser, DocNodeVariant *parent, const HtmlAttribList &attribs)
const HtmlAttribList & attribs () const
int parse (DocNodeVariant *)
Public Member Functions inherited from DocCompoundNode
DocCompoundNode (DocParser *parser, DocNodeVariant *parent)
DocNodeList & children ()
const DocNodeList & children () const
Public Member Functions inherited from DocNode
DocNode (DocParser *parser, DocNodeVariant *parent)
DocNode (const DocNode &)=delete
DocNode & operator= (const DocNode &)=delete
DocNode (DocNode &&)=default
DocNode & operator= (DocNode &&)=default
~DocNode ()=default
DocNodeVariant * parent ()
const DocNodeVariant * parent () const
DocParser * parser ()
const DocParser * parser () const
void setParent (DocNodeVariant *parent)
bool isPreformatted () const
Private Attributes
HtmlAttribList m_attribs
Additional Inherited Members
Protected Types inherited from DocNode
enum RefType { Unknown , Anchor , Section , Table }
Protected Member Functions inherited from DocNode
void setInsidePreformatted (bool p)
Detailed Description
Node Html picture.
Definition at line 842 of file docnode.h.
Constructor & Destructor Documentation
DocHtmlPicture()
DocHtmlPicture::DocHtmlPicture (DocParser * parser, DocNodeVariant * parent, const HtmlAttribList & attribs) inline
Definition at line 845 of file docnode.h.
                                                                                           :
       DocCompoundNode(parser,parent), m_attribs(attribs) {}
Member Function Documentation
attribs()
const HtmlAttribList & DocHtmlPicture::attribs () const inline
Definition at line 847 of file docnode.h.
{ return m_attribs; }
References m_attribs.
Referenced by HtmlDocVisitor::operator()(), and PrintDocVisitor::operator()().
parse()
int DocHtmlPicture::parse (DocNodeVariant * thisVariant)
Definition at line 1338 of file docnode.cpp.
{
  AUTO_TRACE();
  int retval=RetVal_OK;
  int tok;
  while ((tok=parser()->tokenizer.lex()))
  {
    switch (tok)
    {
    case TK_WHITESPACE:
    case TK_NEWPARA:
        continue;
    case TK_HTMLTAG:
      {
        int tagId=Mappers::htmlTagMapper->map(parser()->context.token->name);
        if (tagId==HTML_SOURCE && !parser()->context.token->endTag) // found <source> tag
        {
          AUTO_TRACE_ADD("AddDocHtmlSource");
          children().append<DocHtmlSource>(parser(),thisVariant,parser()->context.token->attribs);
          retval = RetVal_PictureSource;
        }
        else if (tagId==HTML_IMG && !parser()->context.token->endTag) // found <img> tag
        {
          AUTO_TRACE_ADD("AddImg");
          parser()->handleImg(thisVariant,children(),parser()->context.token->attribs);
        }
        else if (tagId==HTML_PICTURE && parser()->context.token->endTag) // found </picture> tag
        {
          AUTO_TRACE_ADD("End picture");
          retval=RetVal_EndHtmlPicture;
          goto endpicture;
        }
        else
        {
          warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"Unexpected html tag <%s%s> found within <picture> context",
              parser()->context.token->endTag?"/":"",qPrint(parser()->context.token->name));
        }
      }
      break;
    default:
      parser()->errorHandleDefaultToken(thisVariant,tok,children(),"<picture> tag");
      break;
    }
  }
endpicture:
  AUTO_TRACE_EXIT("retval={}",DocTokenizer::retvalToString(retval));
  return (retval==RetVal_EndHtmlPicture) ? RetVal_OK : retval;
}
References DocNodeList::append(), TokenInfo::attribs, AUTO_TRACE, AUTO_TRACE_ADD, AUTO_TRACE_EXIT, DocCompoundNode::children(), DocParser::context, TokenInfo::endTag, DocParser::errorHandleDefaultToken(), DocParser::handleImg(), HTML_IMG, HTML_PICTURE, HTML_SOURCE, Mappers::htmlTagMapper, Mapper::map(), DocNode::parser(), qPrint(), RetVal_EndHtmlPicture, RetVal_OK, RetVal_PictureSource, DocTokenizer::retvalToString(), TK_HTMLTAG, TK_NEWPARA, TK_WHITESPACE, DocParserContext::token, and warn_doc_error().
Member Data Documentation
m_attribs
HtmlAttribList DocHtmlPicture::m_attribs private
Definition at line 851 of file docnode.h.
Referenced by attribs().
The documentation for this class was generated from the following files:
/home/runner/work/doxygen/doxygen/src/docnode.h
/home/runner/work/doxygen/doxygen/src/docnode.cpp