Doxygen: GenericNodeListContext Class Reference
GenericNodeListContext Class Reference
standard template list implementation
Public Member Functions
GenericNodeListContext ()
size_t count () const
Returns the number of elements in the list.
TemplateVariant at (size_t index) const
Returns the element at index position index.
TemplateListIntf::ConstIteratorPtr createIterator () const
Creates a new iterator for this list.
void append (const TemplateVariant &ctn)
bool isEmpty () const
Public Member Functions inherited from TemplateListIntf
virtual ~TemplateListIntf ()=default
Destroys the list.
virtual size_t count () const =0
Returns the number of elements in the list.
virtual TemplateVariant at (size_t index) const =0
Returns the element at index position index.
virtual TemplateListIntf::ConstIteratorPtr createIterator () const =0
Creates a new iterator for this list.
Static Public Member Functions
static TemplateListIntfPtr alloc ()
Private Attributes
std::vector< TemplateVariant > m_children
Additional Inherited Members
Public Types inherited from TemplateListIntf
using ConstIteratorPtr = std::unique_ptr< ConstIterator >
Detailed Description
standard template list implementation
Definition at line 189 of file context.cpp.
Constructor & Destructor Documentation
GenericNodeListContext()
GenericNodeListContext::GenericNodeListContext () inline
Definition at line 192 of file context.cpp.
    {
    }
Member Function Documentation
alloc()
static TemplateListIntfPtr GenericNodeListContext::alloc () inline static
Definition at line 195 of file context.cpp.
    {
      return std::static_pointer_cast<TemplateListIntf>(std::make_shared<GenericNodeListContext>());
    }
Referenced by ArgumentListContext::Private::addArgument(), NestingContext::Private::addClass(), InheritanceListContext::Private::addClass(), ClassListContext::Private::addClasses(), NestingContext::Private::addClassHierarchy(), NestingContext::Private::addConcept(), ConceptListContext::Private::addConcepts(), NestingContext::Private::addDerivedClasses(), NestingContext::Private::addDirs(), UsedFilesContext::Private::addFile(), NestingContext::Private::addFiles(), FileListContext::Private::addFiles(), InheritedMemberInfoListContext::Private::addInheritedMembers(), MemberListContext::Private::addMember(), MemberGroupListContext::Private::addMemberGroup(), NestingContext::Private::addMembers(), ModuleListContext::Private::addModules(), NestingContext::Private::addModules(), NestingContext::Private::addNamespace(), NamespaceListContext::Private::addNamespaces(), NestingContext::Private::addPage(), PageListContext::Private::addPages(), ClassContext::Private::createAllMembersList(), MemberContext::Private::createAnonymousMember(), MemberContext::Private::createAnonymousType(), MemberContext::Private::createCategory(), ClassContext::Private::createCategoryOf(), MemberContext::Private::createCategoryRelation(), NestingNodeContext::Private::createClass(), InheritanceNodeContext::Private::createClass(), InheritedMemberInfoContext::Private::createClass(), MemberContext::Private::createClassDef(), ClassContext::Private::createClasses(), NamespaceContext::Private::createClasses(), FileContext::Private::createClasses(), ModuleContext::Private::createClasses(), ClassIndexContext::Private::createClasses(), ConfigContext::Private::createConfigData(), NamespaceContext::Private::createConstantgroups(), FileContext::Private::createConstantgroups(), ModuleContext::Private::createConstantgroups(), ClassHierarchyContext::Private::createDiagrams(), NestingNodeContext::Private::createDir(), DirContext::Private::createDirs(), ModuleContext::Private::createDirs(), MemberContext::Private::createEventAttrs(), ClassContext::Private::createExamples(), MemberContext::Private::createExamples(), ModuleContext::Private::createExamples(), NestingNodeContext::Private::createFile(), IncludeInfoContext::Private::createFileContext(), MemberContext::Private::createFileDef(), DirContext::Private::createFiles(), ModuleContext::Private::createFiles(), MemberContext::Private::createImplementedBy(), MemberContext::Private::createImplements(), ClassContext::Private::createIncludeInfo(), ConceptContext::Private::createIncludeInfo(), FileContext::Private::createIncludeList(), ClassContext::Private::createInheritedByList(), InheritedMemberInfoContext::Private::createInheritedFrom(), ClassContext::Private::createInheritsList(), NamespaceContext::Private::createInlineClasses(), FileContext::Private::createInlineClasses(), ModuleContext::Private::createInlineClasses(), ClassContext::Private::createInnerClasses(), MemberContext::Private::createLabels(), NestingNodeContext::Private::createMember(), MemberInfoContext::Private::createMember(), ClassContext::Private::createMemberList(), NamespaceContext::Private::createMemberList(), FileContext::Private::createMemberList(), ModuleContext::Private::createMemberList(), GlobalsIndexContext::Private::createMembersFiltered(), ClassMembersIndexContext::Private::createMembersFiltered(), NamespaceMembersIndexContext::Private::createMembersFiltered(), NestingNodeContext::Private::createModule(), ModuleContext::Private::createModules(), NestingNodeContext::Private::createNamespace(), MemberContext::Private::createNamespaceDef(), NamespaceContext::Private::createNamespaces(), FileContext::Private::createNamespaces(), ModuleContext::Private::createNamespaces(), DefinitionContext< T >::createNavigationPath(), NestingNodeContext::Private::createPage(), ModuleContext::Private::createPages(), DefinitionContext< T >::createPartOfGroups(), MemberContext::Private::createPropertyAttrs(), MemberContext::Private::createReimplementedBy(), MemberContext::Private::createReimplements(), SymbolIndexContext::Private::createSymbolGroups(), SearchIndexContext::Private::createSymbolIndices(), SymbolGroupContext::Private::createSymbolList(), ClassContext::Private::createTemplateDecls(), MemberContext::Private::createTemplateDecls(), ConceptContext::Private::createTemplateDecls(), ClassContext::Private::createUsedFiles(), DefinitionContext< T >::DefinitionContext(), DefinitionContext< T >::fillPath(), generateOutputViaTemplate(), ClassHierarchyContext::Private::Private(), ClassTreeContext::Private::Private(), NamespaceTreeContext::Private::Private(), DirListContext::Private::Private(), FileTreeContext::Private::Private(), ExampleListContext::Private::Private(), ConceptTreeContext::Private::Private(), ModuleTreeContext::Private::Private(), ExampleTreeContext::Private::Private(), SearchIndicesContext::Private::Private(), IncludeInfoListContext::Private::Private(), AllMembersListContext::Private::Private(), NestingNodeContext::Private::Private(), PageTreeContext::Private::Private(), SymbolIndicesContext::Private::Private(), SymbolGroupListContext::Private::Private(), and SymbolListContext::Private::Private().
append()
void GenericNodeListContext::append (const TemplateVariant & ctn) inline
Definition at line 219 of file context.cpp.
    {
      m_children.emplace_back(ctn);
    }
References m_children.
Referenced by ArgumentListContext::Private::addArgument(), NestingContext::Private::addClass(), InheritanceListContext::Private::addClass(), ClassListContext::Private::addClasses(), NestingContext::Private::addClassHierarchy(), NestingContext::Private::addConcept(), ConceptListContext::Private::addConcepts(), NestingContext::Private::addDerivedClasses(), NestingContext::Private::addDirs(), UsedFilesContext::Private::addFile(), NestingContext::Private::addFiles(), FileListContext::Private::addFiles(), InheritedMemberInfoListContext::Private::addInheritedMembers(), MemberListContext::Private::addMember(), MemberGroupListContext::Private::addMemberGroup(), NestingContext::Private::addMembers(), ModuleListContext::Private::addModules(), NestingContext::Private::addModules(), NestingContext::Private::addNamespace(), NamespaceListContext::Private::addNamespaces(), NestingContext::Private::addPage(), PageListContext::Private::addPages(), DirListContext::Private::Private(), ExampleListContext::Private::Private(), SearchIndicesContext::Private::Private(), IncludeInfoListContext::Private::Private(), AllMembersListContext::Private::Private(), SymbolIndicesContext::Private::Private(), SymbolGroupListContext::Private::Private(), and SymbolListContext::Private::Private().
at()
TemplateVariant GenericNodeListContext::at (size_t index) const inline virtual
Returns the element at index position index.
Implements TemplateListIntf.
Definition at line 205 of file context.cpp.
    {
      TemplateVariant result;
      if (index<count())
      {
        result = m_children[index];
      }
      return result;
    }
References count(), and m_children.
count()
size_t GenericNodeListContext::count () const inline virtual
Returns the number of elements in the list.
Implements TemplateListIntf.
Definition at line 201 of file context.cpp.
    {
      return m_children.size();
    }
References m_children.
Referenced by InheritedMemberInfoListContext::Private::addInheritedMembers(), and at().
createIterator()
TemplateListIntf::ConstIteratorPtr GenericNodeListContext::createIterator () const inline virtual
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implements TemplateListIntf.
Definition at line 214 of file context.cpp.
    {
      return std::make_unique<GenericConstIterator>(m_children);
    }
References m_children.
isEmpty()
bool GenericNodeListContext::isEmpty () const inline
Definition at line 223 of file context.cpp.
    {
      return m_children.empty();
    }
References m_children.
Member Data Documentation
m_children
std::vector< TemplateVariant > GenericNodeListContext::m_children private
Definition at line 228 of file context.cpp.
Referenced by append(), at(), count(), createIterator(), and isEmpty().
The documentation for this class was generated from the following file:
src/context.cpp