Doxygen: src/docnode.h File Reference
docnode.h File Reference
#include <stdio.h>
#include <vector>
#include <memory>
#include <variant>
#include "qcstring.h"
#include "docvisitor.h"
#include "docparser.h"
#include "htmlattrib.h"
#include "htmlentity.h"
#include "growvector.h"
Classes
class DocNode
Abstract node interface with type information.
struct DocNodeList
class DocCompoundNode
Base class for nodes with children.
class DocWord
Node representing a word.
class DocLinkedWord
Node representing a word that can be linked to something.
class DocURL
Node representing a URL (or email address)
class DocLineBreak
Node representing a line break.
class DocHorRuler
Node representing a horizontal ruler.
class DocAnchor
Node representing an anchor.
class DocCite
Node representing a citation of some bibliographic reference.
class DocStyleChange
Node representing a style change.
class DocSymbol
Node representing a special symbol.
class DocEmoji
Node representing an emoji.
class DocWhiteSpace
Node representing some amount of white space.
class DocSeparator
Node representing a separator.
class DocVerbatim
Node representing a verbatim, unparsed text fragment.
struct DocVerbatim::Private
class DocInclude
Node representing an included text block from file.
class DocIncOperator
Node representing a include/dontinclude operator block.
class DocFormula
Node representing an item of a cross-referenced list.
class DocIndexEntry
Node representing an entry in the index.
class DocAutoList
Node representing an auto List.
class DocAutoListItem
Node representing an item of a auto list.
class DocTitle
Node representing a simple section title.
class DocXRefItem
Node representing an item of a cross-referenced list.
class DocImage
Node representing an image.
struct DocImage::Private
class DocDiagramFileBase
struct DocDiagramFileBase::Private
class DocDotFile
Node representing a dot file.
class DocMscFile
Node representing a msc file.
class DocDiaFile
Node representing a dia file.
class DocVhdlFlow
Node representing a VHDL flow chart.
class DocLink
Node representing a link to some item.
class DocRef
Node representing a reference to some item.
class DocInternalRef
Node representing an internal reference to some item.
class DocHRef
Node representing a Hypertext reference.
class DocHtmlDetails
Node Html details.
class DocHtmlHeader
Node Html heading.
class DocHtmlDescTitle
Node representing a Html description item.
class DocHtmlDescList
Node representing a Html description list.
class DocSection
Node representing a normal section.
class DocSecRefItem
Node representing a reference to a section.
class DocSecRefList
Node representing a list of section references.
class DocInternal
Node representing an internal section of documentation.
class DocParBlock
Node representing an block of paragraphs.
class DocSimpleList
Node representing a simple list.
class DocHtmlList
Node representing a Html list.
class DocSimpleSect
Node representing a simple section.
class DocSimpleSectSep
Node representing a separator between two simple sections of the same type.
class DocParamSect
Node representing a parameter section.
class DocPara
Node representing a paragraph in the documentation tree.
class DocParamList
Node representing a parameter list.
class DocSimpleListItem
Node representing a simple list item.
class DocHtmlListItem
Node representing a HTML list item.
class DocHtmlDescData
Node representing a HTML description data.
class DocHtmlCell
Node representing a HTML table cell.
class DocHtmlCaption
Node representing a HTML table caption.
class DocHtmlRow
Node representing a HTML table row.
class DocHtmlTable
Node representing a HTML table.
class DocHtmlBlockQuote
Node representing an HTML blockquote.
class DocText
Root node of a text fragment.
class DocRoot
Root node of documentation tree.
struct details::Impl< T, Ts >
struct details::Impl< T >
class DocNodeAST
Class representing the abstract syntax tree of a documentation block.
Namespaces
namespace details
Macros
#define DOC_NODES
#define DN(x) class x;
#define DN_SEP
#define DN(x) x
#define DN_SEP ,
#define DN(x) constexpr const char *docNodeName(const x &n) { return #x; }
#define DN_SEP
#define DN(x) #x
#define DN_SEP ,
#define DN(x) #x
#define DN_SEP ,
#define DN(x) sizeof(x)
#define DN_SEP ,
Typedefs
using DocNodeVariant = std::variant< #define DN(x) #define DN_SEP DOC_NODES >
Functions
constexpr const DocNodeVariant * parent (const DocNodeVariant *n)
returns the parent node of a given node n or 0 if the node has no parent.
template<class... Ts>
constexpr bool holds_one_of_alternatives (const DocNodeVariant &v)
returns true iff v holds one of types passed as template parameters
const char * docNodeName (const DocNodeVariant &v)
-------------— Debug helpers ----------------------------—
void dumpDocNodeSizes ()
void dumpDocNodeList (const DocNodeList &children)
Macro Definition Documentation
DN [1/6]
#define DN (x) class x;
Definition at line 68 of file docnode.h.
DN [2/6]
#define DN (x) x
Definition at line 68 of file docnode.h.
DN [3/6]
#define DN (x) constexpr const char *docNodeName(const x &n) { return #x; }
Definition at line 68 of file docnode.h.
DN [4/6]
#define DN (x) #x
Definition at line 68 of file docnode.h.
DN [5/6]
#define DN (x) #x
Definition at line 68 of file docnode.h.
DN [6/6]
#define DN (x) sizeof(x)
Definition at line 68 of file docnode.h.
DN_SEP [1/6]
#define DN_SEP
Definition at line 69 of file docnode.h.
DN_SEP [2/6]
#define DN_SEP ,
Definition at line 69 of file docnode.h.
DN_SEP [3/6]
#define DN_SEP
Definition at line 69 of file docnode.h.
DN_SEP [4/6]
#define DN_SEP ,
Definition at line 69 of file docnode.h.
DN_SEP [5/6]
#define DN_SEP ,
Definition at line 69 of file docnode.h.
DN_SEP [6/6]
#define DN_SEP ,
Definition at line 69 of file docnode.h.
DOC_NODES
#define DOC_NODES
Value:
/*  0 */  DN(DocWord)           DN_SEP DN(DocLinkedWord)    DN_SEP DN(DocURL)            DN_SEP DN(DocLineBreak)    DN_SEP DN(DocHorRuler)    DN_SEP   \
/*  5 */  DN(DocAnchor)         DN_SEP DN(DocCite)          DN_SEP DN(DocStyleChange)    DN_SEP DN(DocSymbol)       DN_SEP DN(DocEmoji)       DN_SEP   \
/* 10 */  DN(DocWhiteSpace)     DN_SEP DN(DocSeparator)     DN_SEP DN(DocVerbatim)       DN_SEP DN(DocInclude)      DN_SEP DN(DocIncOperator) DN_SEP   \
/* 15 */  DN(DocFormula)        DN_SEP DN(DocIndexEntry)    DN_SEP DN(DocAutoList)       DN_SEP DN(DocAutoListItem) DN_SEP DN(DocTitle)       DN_SEP   \
/* 20 */  DN(DocXRefItem)       DN_SEP DN(DocImage)         DN_SEP DN(DocDotFile)        DN_SEP DN(DocMscFile)      DN_SEP DN(DocDiaFile)     DN_SEP   \
/* 25 */  DN(DocVhdlFlow)       DN_SEP DN(DocLink)          DN_SEP DN(DocRef)            DN_SEP DN(DocInternalRef)  DN_SEP DN(DocHRef)        DN_SEP   \
/* 30 */  DN(DocHtmlHeader)     DN_SEP DN(DocHtmlDescTitle) DN_SEP DN(DocHtmlDescList)   DN_SEP DN(DocSection)      DN_SEP DN(DocSecRefItem)  DN_SEP   \
/* 35 */  DN(DocSecRefList)     DN_SEP DN(DocInternal)      DN_SEP DN(DocParBlock)       DN_SEP DN(DocSimpleList)   DN_SEP DN(DocHtmlList)    DN_SEP   \
/* 40 */  DN(DocSimpleSect)     DN_SEP DN(DocSimpleSectSep) DN_SEP DN(DocParamSect)      DN_SEP DN(DocPara)         DN_SEP DN(DocParamList)   DN_SEP   \
/* 45 */  DN(DocSimpleListItem) DN_SEP DN(DocHtmlListItem)  DN_SEP DN(DocHtmlDescData)   DN_SEP DN(DocHtmlCell)     DN_SEP DN(DocHtmlCaption) DN_SEP   \
/* 50 */  DN(DocHtmlRow)        DN_SEP DN(DocHtmlTable)     DN_SEP DN(DocHtmlBlockQuote) DN_SEP DN(DocText)         DN_SEP DN(DocRoot)        DN_SEP   \
/* 55 */  DN(DocHtmlDetails)                                                                                                                           \
Definition at line 37 of file docnode.h.
Typedef Documentation
DocNodeVariant
using DocNodeVariant = std::variant< #define DN(x) #define DN_SEP DOC_NODES >
Definition at line 59 of file docnode.h.
Function Documentation
docNodeName()
const char * docNodeName (const DocNodeVariant & v) inline
-------------— Debug helpers ----------------------------—
Definition at line 1330 of file docnode.h.
{
#define DN(x)  #x
#define DN_SEP ,
  static const char *table[] = { DOC_NODES };
#undef DN
#undef DN_SEP
  return table[v.index()];
}
References DOC_NODES.
Referenced by dumpDocNodeList().
dumpDocNodeList()
void dumpDocNodeList (const DocNodeList & children) inline
Definition at line 1364 of file docnode.h.
{
  printf("children=[\n");
  for (const auto &child : children)
  {
    const DocWord *w = std::get_if<DocWord>(&child);
    printf("  %s (%p) %s\n",docNodeName(child),(void*)&child,qPrint(w?w->word():""));
  }
  printf("]\n");
}
References docNodeName(), qPrint(), and DocWord::word().
dumpDocNodeSizes()
void dumpDocNodeSizes () inline
Definition at line 1340 of file docnode.h.
{
#define DN(x)  #x
#define DN_SEP ,
  static const char *tableWithNames[] = { DOC_NODES };
#undef DN
#undef DN_SEP
#define DN(x)  sizeof(x)
#define DN_SEP ,
  static size_t tableWithSizes[] = { DOC_NODES };
#undef DN
#undef DN_SEP
  size_t maxSize=0;
  printf("DocNodeVariant(\n");
  for (size_t i=0;i<sizeof(tableWithNames)/sizeof(tableWithNames[0]);i++)
  {
    printf("  /* %2zu */ sizeof(%s)=%zu\n",i,tableWithNames[i],tableWithSizes[i]);
    if (tableWithSizes[i]>maxSize) maxSize = tableWithSizes[i];
  }
  printf(")=%zu\n",maxSize);
}
References DOC_NODES.
holds_one_of_alternatives()
template<class... Ts> constexpr bool holds_one_of_alternatives (const DocNodeVariant & v) constexpr
returns true iff v holds one of types passed as template parameters
Definition at line 1299 of file docnode.h.
{
  return details::Impl<Ts...>::holds_one_of_alternatives(v);
}
References details::Impl< T, Ts >::holds_one_of_alternatives().
Referenced by determineIfNeedsTag(), mustBeOutsideParagraph(), and DocPara::parse().
parent()
constexpr const DocNodeVariant * parent (const DocNodeVariant * n) constexpr
returns the parent node of a given node n or 0 if the node has no parent.
Definition at line 1269 of file docnode.h.
{
  return n ? std::visit([](auto &&x)->decltype(auto) { return x.parent(); }, *n) : nullptr;
}
Referenced by TemplateContextImpl::addIndexEntry(), ClassContext::Private::addTemplateDecls(), NestingNodeContext::alloc(), NestingContext::alloc(), buildDirectories(), TemplateNodeFactory::create(), FTVHelp::decContentsDepth(), DocParser::defaultHandleTitleAndSize(), DocParser::defaultHandleToken(), TreeDiagram::drawConnectors(), dupOfParent(), DocParser::errorHandleDefaultToken(), externalLinkTarget(), generateIndent(), generateIndentLabel(), getParagraphContext(), getPathListFunc(), DocParser::handleAHref(), DocParser::handleAnchor(), DocParser::handleImage(), DocParser::handleImg(), DocParser::handleInitialStyleCommands(), DocParser::handleInternalRef(), DocParser::handleLinkedWord(), DocParser::handleParameterType(), DocParser::handlePendingStyleCommands(), DocParser::handleStyleArgument(), DocParser::handleStyleEnter(), DocParser::handleStyleLeave(), DiagramRow::insertClass(), insideDetails(), insideLI(), insideOL(), insidePRE(), insideTable(), insideUL(), DocParser::internalValidatingParseDoc(), isFirstChildNode(), isLastChildNode(), isParentScope(), isSeparatedParagraph(), isSymbolHidden(), listIsNested(), LatexDocVisitor::operator()(), parentIsVisible(), TemplateParser::parse(), pathToNode(), tableIsNested(), and writeDotDirDepGraph().