Doxygen: /home/runner/work/doxygen/doxygen/src/index.h File Reference
index.h File Reference
#include <memory>
#include "qcstring.h"
Classes
class Index
Namespaces
namespace ClassMemberHighlight
namespace FileMemberHighlight
namespace NamespaceMemberHighlight
Enumerations
enum class IndexSection {
isTitlePageStart , isTitlePageAuthor , isMainPage , isModuleIndex ,
isDirIndex , isNamespaceIndex , isConceptIndex , isClassHierarchyIndex ,
isCompoundIndex , isFileIndex , isPageIndex , isModuleDocumentation ,
isDirDocumentation , isNamespaceDocumentation , isClassDocumentation , isConceptDocumentation ,
isFileDocumentation , isExampleDocumentation , isPageDocumentation , isPageDocumentation2 ,
isEndIndex
}
enum class HighlightedItem {
None =0 , Main , Modules , Namespaces ,
ClassHierarchy , InterfaceHierarchy , ExceptionHierarchy , Classes ,
Concepts , Interfaces , Structs , Exceptions ,
AnnotatedClasses , AnnotatedInterfaces , AnnotatedStructs , AnnotatedExceptions ,
Files , NamespaceMembers , Functions , Globals ,
Pages , Examples , Search , UserGroup ,
ClassVisible , ConceptVisible , InterfaceVisible , StructVisible ,
ExceptionVisible , NamespaceVisible , FileVisible
}
enum ClassMemberHighlight::Enum : int {
ClassMemberHighlight::All = 0 , ClassMemberHighlight::Functions , ClassMemberHighlight::Variables , ClassMemberHighlight::Typedefs ,
ClassMemberHighlight::Enums , ClassMemberHighlight::EnumValues , ClassMemberHighlight::Properties , ClassMemberHighlight::Events ,
ClassMemberHighlight::Related , ClassMemberHighlight::Total
}
enum FileMemberHighlight::Enum : int {
FileMemberHighlight::All = 0 , FileMemberHighlight::Functions , FileMemberHighlight::Variables , FileMemberHighlight::Typedefs ,
FileMemberHighlight::Sequences , FileMemberHighlight::Dictionaries , FileMemberHighlight::Enums , FileMemberHighlight::EnumValues ,
FileMemberHighlight::Defines , FileMemberHighlight::Total
}
enum NamespaceMemberHighlight::Enum : int {
NamespaceMemberHighlight::All = 0 , NamespaceMemberHighlight::Functions , NamespaceMemberHighlight::Variables , NamespaceMemberHighlight::Typedefs ,
NamespaceMemberHighlight::Sequences , NamespaceMemberHighlight::Dictionaries , NamespaceMemberHighlight::Enums , NamespaceMemberHighlight::EnumValues ,
NamespaceMemberHighlight::Total
}
Functions
void writeGraphInfo (OutputList &ol)
void writeIndexHierarchy (OutputList &ol)
void startTitle (OutputList &ol, const QCString &fileName, const DefinitionMutable *def=0)
void endTitle (OutputList &ol, const QCString &fileName, const QCString &name)
void startFile (OutputList &ol, const QCString &name, const QCString &manName, const QCString &title, HighlightedItem hli=HighlightedItem::None, bool additionalIndices=FALSE, const QCString &altSidebarName=QCString())
void endFile (OutputList &ol, bool skipNavIndex=FALSE, bool skipEndContents=FALSE, const QCString &navPath=QCString())
void endFileWithNavPath (const Definition *d, OutputList &ol)
void initClassMemberIndices ()
void initFileMemberIndices ()
void initNamespaceMemberIndices ()
void addClassMemberNameToIndex (const MemberDef *md)
void addFileMemberNameToIndex (const MemberDef *md)
void addNamespaceMemberNameToIndex (const MemberDef *md)
void sortMemberIndexLists ()
QCString fixSpaces (const QCString &s)
int countVisibleMembers (const NamespaceDef *nd)
Enumeration Type Documentation
HighlightedItem
enum class HighlightedItem strong
Enumerator
None
Main
Modules
Namespaces
ClassHierarchy
InterfaceHierarchy
ExceptionHierarchy
Classes
Concepts
Interfaces
Structs
Exceptions
AnnotatedClasses
AnnotatedInterfaces
AnnotatedStructs
AnnotatedExceptions
Files
NamespaceMembers
Functions
Globals
Pages
Examples
Search
UserGroup
ClassVisible
ConceptVisible
InterfaceVisible
StructVisible
ExceptionVisible
NamespaceVisible
FileVisible
Definition at line 53 of file index.h.
{
  None=0,
  Main,
  Modules,
  Namespaces,
  ClassHierarchy,
  InterfaceHierarchy,
  ExceptionHierarchy,
  Classes,
  Concepts,
  Interfaces,
  Structs,
  Exceptions,
  AnnotatedClasses,
  AnnotatedInterfaces,
  AnnotatedStructs,
  AnnotatedExceptions,
  Files,
  NamespaceMembers,
  Functions,
  Globals,
  Pages,
  Examples,
  Search,
  UserGroup,
  ClassVisible,
  ConceptVisible,
  InterfaceVisible,
  StructVisible,
  ExceptionVisible,
  NamespaceVisible,
  FileVisible
};
IndexSection
enum class IndexSection strong
Enumerator
isTitlePageStart
isTitlePageAuthor
isMainPage
isModuleIndex
isDirIndex
isNamespaceIndex
isConceptIndex
isClassHierarchyIndex
isCompoundIndex
isFileIndex
isPageIndex
isModuleDocumentation
isDirDocumentation
isNamespaceDocumentation
isClassDocumentation
isConceptDocumentation
isFileDocumentation
isExampleDocumentation
isPageDocumentation
isPageDocumentation2
isEndIndex
Definition at line 28 of file index.h.
{
  isTitlePageStart,
  isTitlePageAuthor,
  isMainPage,
  isModuleIndex,
  isDirIndex,
  isNamespaceIndex,
  isConceptIndex,
  isClassHierarchyIndex,
  isCompoundIndex,
  isFileIndex,
  isPageIndex,
  isModuleDocumentation,
  isDirDocumentation,
  isNamespaceDocumentation,
  isClassDocumentation,
  isConceptDocumentation,
  isFileDocumentation,
  isExampleDocumentation,
  isPageDocumentation,
  isPageDocumentation2,
  isEndIndex
};
Function Documentation
addClassMemberNameToIndex()
void addClassMemberNameToIndex (const MemberDef * md)
Definition at line 2713 of file index.cpp.
{
  Index &index = Index::instance();
  bool hideFriendCompounds = Config_getBool(HIDE_FRIEND_COMPOUNDS);
  const ClassDef *cd=0;
  if (md->isLinkableInProject() &&
      (cd=md->getClassDef())    &&
      cd->isLinkableInProject() &&
      cd->templateMaster()==0)
  {
    QCString n = md->name();
    std::string letter = getUTF8CharAt(n.str(),getPrefixIndex(n));
    if (!letter.empty())
    {
      letter = convertUTF8ToLower(letter);
      bool isFriendToHide = hideFriendCompounds &&
        (QCString(md->typeString())=="friend class" ||
         QCString(md->typeString())=="friend struct" ||
         QCString(md->typeString())=="friend union");
      if (!(md->isFriend() && isFriendToHide) &&
          (!md->isEnumValue() || (md->getEnumScope() && !md->getEnumScope()->isStrong()))
         )
      {
        MemberIndexMap_add(g_classIndexLetterUsed[ClassMemberHighlight::All],letter,md);
        index.incrementDocumentedClassMembers(ClassMemberHighlight::All);
      }
      if (md->isFunction()  || md->isSlot() || md->isSignal())
      {
        MemberIndexMap_add(g_classIndexLetterUsed[ClassMemberHighlight::Functions],letter,md);
        index.incrementDocumentedClassMembers(ClassMemberHighlight::Functions);
      }
      else if (md->isVariable())
      {
        MemberIndexMap_add(g_classIndexLetterUsed[ClassMemberHighlight::Variables],letter,md);
        index.incrementDocumentedClassMembers(ClassMemberHighlight::Variables);
      }
      else if (md->isTypedef())
      {
        MemberIndexMap_add(g_classIndexLetterUsed[ClassMemberHighlight::Typedefs],letter,md);
        index.incrementDocumentedClassMembers(ClassMemberHighlight::Typedefs);
      }
      else if (md->isEnumerate())
      {
        MemberIndexMap_add(g_classIndexLetterUsed[ClassMemberHighlight::Enums],letter,md);
        index.incrementDocumentedClassMembers(ClassMemberHighlight::Enums);
      }
      else if (md->isEnumValue() && md->getEnumScope() && !md->getEnumScope()->isStrong())
      {
        MemberIndexMap_add(g_classIndexLetterUsed[ClassMemberHighlight::EnumValues],letter,md);
        index.incrementDocumentedClassMembers(ClassMemberHighlight::EnumValues);
      }
      else if (md->isProperty())
      {
        MemberIndexMap_add(g_classIndexLetterUsed[ClassMemberHighlight::Properties],letter,md);
        index.incrementDocumentedClassMembers(ClassMemberHighlight::Properties);
      }
      else if (md->isEvent())
      {
        MemberIndexMap_add(g_classIndexLetterUsed[ClassMemberHighlight::Events],letter,md);
        index.incrementDocumentedClassMembers(ClassMemberHighlight::Events);
      }
      else if (md->isRelated() || md->isForeign() ||
               (md->isFriend() && !isFriendToHide))
      {
        MemberIndexMap_add(g_classIndexLetterUsed[ClassMemberHighlight::Related],letter,md);
        index.incrementDocumentedClassMembers(ClassMemberHighlight::Related);
      }
    }
  }
}
References ClassMemberHighlight::All, Config_getBool, convertUTF8ToLower(), ClassMemberHighlight::Enums, ClassMemberHighlight::EnumValues, ClassMemberHighlight::Events, ClassMemberHighlight::Functions, g_classIndexLetterUsed, MemberDef::getClassDef(), MemberDef::getEnumScope(), getPrefixIndex(), getUTF8CharAt(), Index::incrementDocumentedClassMembers(), Index::instance(), MemberDef::isEnumerate(), MemberDef::isEnumValue(), MemberDef::isEvent(), MemberDef::isForeign(), MemberDef::isFriend(), MemberDef::isFunction(), ClassDef::isLinkableInProject(), MemberDef::isLinkableInProject(), MemberDef::isProperty(), MemberDef::isRelated(), MemberDef::isSignal(), MemberDef::isSlot(), MemberDef::isStrong(), MemberDef::isTypedef(), MemberDef::isVariable(), MemberIndexMap_add(), Definition::name(), ClassMemberHighlight::Properties, ClassMemberHighlight::Related, QCString::str(), ClassDef::templateMaster(), ClassMemberHighlight::Typedefs, MemberDef::typeString(), and ClassMemberHighlight::Variables.
Referenced by addMembersToIndex().
addFileMemberNameToIndex()
void addFileMemberNameToIndex (const MemberDef * md)
Definition at line 2867 of file index.cpp.
{
  Index &index = Index::instance();
  const FileDef *fd=md->getFileDef();
  if (fd && fd->isLinkableInProject() && md->isLinkableInProject())
  {
    QCString n = md->name();
    std::string letter = getUTF8CharAt(n.str(),getPrefixIndex(n));
    if (!letter.empty())
    {
      letter = convertUTF8ToLower(letter);
      if (!md->isEnumValue() || (md->getEnumScope() && !md->getEnumScope()->isStrong()))
      {
        MemberIndexMap_add(g_fileIndexLetterUsed[FileMemberHighlight::All],letter,md);
        index.incrementDocumentedFileMembers(FileMemberHighlight::All);
      }
      if (md->isFunction())
      {
        MemberIndexMap_add(g_fileIndexLetterUsed[FileMemberHighlight::Functions],letter,md);
        index.incrementDocumentedFileMembers(FileMemberHighlight::Functions);
      }
      else if (md->isVariable())
      {
        MemberIndexMap_add(g_fileIndexLetterUsed[FileMemberHighlight::Variables],letter,md);
        index.incrementDocumentedFileMembers(FileMemberHighlight::Variables);
      }
      else if (md->isTypedef())
      {
        MemberIndexMap_add(g_fileIndexLetterUsed[FileMemberHighlight::Typedefs],letter,md);
        index.incrementDocumentedFileMembers(FileMemberHighlight::Typedefs);
      }
      else if (md->isSequence())
      {
        MemberIndexMap_add(g_fileIndexLetterUsed[FileMemberHighlight::Sequences],letter,md);
        index.incrementDocumentedFileMembers(FileMemberHighlight::Sequences);
      }
      else if (md->isDictionary())
      {
        MemberIndexMap_add(g_fileIndexLetterUsed[FileMemberHighlight::Dictionaries],letter,md);
        index.incrementDocumentedFileMembers(FileMemberHighlight::Dictionaries);
      }
      else if (md->isEnumerate())
      {
        MemberIndexMap_add(g_fileIndexLetterUsed[FileMemberHighlight::Enums],letter,md);
        index.incrementDocumentedFileMembers(FileMemberHighlight::Enums);
      }
      else if (md->isEnumValue() && md->getEnumScope() && !md->getEnumScope()->isStrong())
      {
        MemberIndexMap_add(g_fileIndexLetterUsed[FileMemberHighlight::EnumValues],letter,md);
        index.incrementDocumentedFileMembers(FileMemberHighlight::EnumValues);
      }
      else if (md->isDefine())
      {
        MemberIndexMap_add(g_fileIndexLetterUsed[FileMemberHighlight::Defines],letter,md);
        index.incrementDocumentedFileMembers(FileMemberHighlight::Defines);
      }
    }
  }
}
References FileMemberHighlight::All, convertUTF8ToLower(), FileMemberHighlight::Defines, FileMemberHighlight::Dictionaries, FileMemberHighlight::Enums, FileMemberHighlight::EnumValues, FileMemberHighlight::Functions, g_fileIndexLetterUsed, MemberDef::getEnumScope(), MemberDef::getFileDef(), getPrefixIndex(), getUTF8CharAt(), Index::incrementDocumentedFileMembers(), Index::instance(), MemberDef::isDefine(), MemberDef::isDictionary(), MemberDef::isEnumerate(), MemberDef::isEnumValue(), MemberDef::isFunction(), FileDef::isLinkableInProject(), MemberDef::isLinkableInProject(), MemberDef::isSequence(), MemberDef::isStrong(), MemberDef::isTypedef(), MemberDef::isVariable(), MemberIndexMap_add(), Definition::name(), FileMemberHighlight::Sequences, QCString::str(), FileMemberHighlight::Typedefs, and FileMemberHighlight::Variables.
Referenced by addMembersToIndex().
addNamespaceMemberNameToIndex()
void addNamespaceMemberNameToIndex (const MemberDef * md)
Definition at line 2798 of file index.cpp.
{
  Index &index = Index::instance();
  const NamespaceDef *nd=md->getNamespaceDef();
  if (nd && nd->isLinkableInProject() && md->isLinkableInProject())
  {
    QCString n = md->name();
    std::string letter = getUTF8CharAt(n.str(),getPrefixIndex(n));
    if (!letter.empty())
    {
      letter = convertUTF8ToLower(letter);
      if (!md->isEnumValue() || (md->getEnumScope() && !md->getEnumScope()->isStrong()))
      {
        MemberIndexMap_add(g_namespaceIndexLetterUsed[NamespaceMemberHighlight::All],letter,md);
        index.incrementDocumentedNamespaceMembers(NamespaceMemberHighlight::All);
      }
      if (md->isFunction())
      {
        MemberIndexMap_add(g_namespaceIndexLetterUsed[NamespaceMemberHighlight::Functions],letter,md);
        index.incrementDocumentedNamespaceMembers(NamespaceMemberHighlight::Functions);
      }
      else if (md->isVariable())
      {
        MemberIndexMap_add(g_namespaceIndexLetterUsed[NamespaceMemberHighlight::Variables],letter,md);
        index.incrementDocumentedNamespaceMembers(NamespaceMemberHighlight::Variables);
      }
      else if (md->isTypedef())
      {
        MemberIndexMap_add(g_namespaceIndexLetterUsed[NamespaceMemberHighlight::Typedefs],letter,md);
        index.incrementDocumentedNamespaceMembers(NamespaceMemberHighlight::Typedefs);
      }
      else if (md->isSequence())
      {
        MemberIndexMap_add(g_namespaceIndexLetterUsed[NamespaceMemberHighlight::Sequences],letter,md);
        index.incrementDocumentedNamespaceMembers(NamespaceMemberHighlight::Sequences);
      }
      else if (md->isDictionary())
      {
        MemberIndexMap_add(g_namespaceIndexLetterUsed[NamespaceMemberHighlight::Dictionaries],letter,md);
        index.incrementDocumentedNamespaceMembers(NamespaceMemberHighlight::Dictionaries);
      }
      else if (md->isEnumerate())
      {
        MemberIndexMap_add(g_namespaceIndexLetterUsed[NamespaceMemberHighlight::Enums],letter,md);
        index.incrementDocumentedNamespaceMembers(NamespaceMemberHighlight::Enums);
      }
      else if (md->isEnumValue() && md->getEnumScope() && !md->getEnumScope()->isStrong())
      {
        MemberIndexMap_add(g_namespaceIndexLetterUsed[NamespaceMemberHighlight::EnumValues],letter,md);
        index.incrementDocumentedNamespaceMembers(NamespaceMemberHighlight::EnumValues);
      }
    }
  }
}
References NamespaceMemberHighlight::All, convertUTF8ToLower(), NamespaceMemberHighlight::Dictionaries, NamespaceMemberHighlight::Enums, NamespaceMemberHighlight::EnumValues, NamespaceMemberHighlight::Functions, g_namespaceIndexLetterUsed, MemberDef::getEnumScope(), MemberDef::getNamespaceDef(), getPrefixIndex(), getUTF8CharAt(), Index::incrementDocumentedNamespaceMembers(), Index::instance(), MemberDef::isDictionary(), MemberDef::isEnumerate(), MemberDef::isEnumValue(), MemberDef::isFunction(), MemberDef::isLinkableInProject(), NamespaceDef::isLinkableInProject(), MemberDef::isSequence(), MemberDef::isStrong(), MemberDef::isTypedef(), MemberDef::isVariable(), MemberIndexMap_add(), Definition::name(), NamespaceMemberHighlight::Sequences, QCString::str(), NamespaceMemberHighlight::Typedefs, and NamespaceMemberHighlight::Variables.
Referenced by addMembersToIndex().
countVisibleMembers()
int countVisibleMembers (const NamespaceDef * nd)
Definition at line 1632 of file index.cpp.
{
  int count=0;
  for (const auto &lde : LayoutDocManager::instance().docEntries(LayoutDocManager::Namespace))
  {
    if (lde->kind()==LayoutDocEntry::MemberDef)
    {
      const LayoutDocEntryMemberDef *lmd = dynamic_cast<const LayoutDocEntryMemberDef*>(lde.get());
      if (lmd)
      {
        MemberList *ml = nd->getMemberList(lmd->type);
        if (ml)
        {
          for (const auto &md : *ml)
          {
            if (md->visibleInIndex())
            {
              count++;
            }
          }
        }
      }
    }
  }
  return count;
}
References NamespaceDef::getMemberList(), LayoutDocManager::instance(), LayoutDocEntry::MemberDef, LayoutDocManager::Namespace, and LayoutDocEntryMemberDef::type.
Referenced by NestingContext::Private::addNamespace(), and writeNamespaceTreeElement().
endFile()
void endFile (OutputList & ol, bool skipNavIndex = FALSE, bool skipEndContents = FALSE, const QCString & navPath = QCString())
Definition at line 301 of file index.cpp.
{
  bool generateTreeView = Config_getBool(GENERATE_TREEVIEW);
  ol.pushGeneratorState();
  ol.disableAllBut(OutputType::Html);
  if (!skipNavIndex)
  {
    if (!skipEndContents) ol.endContents();
    if (generateTreeView)
    {
      ol.writeString("</div><!-- doc-content -->\n");
    }
  }
  ol.writeFooter(navPath); // write the footer
  ol.popGeneratorState();
  ol.endFile();
}
References Config_getBool, OutputList::disableAllBut(), OutputList::endContents(), OutputList::endFile(), Html, OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputList::writeFooter(), and OutputList::writeString().
Referenced by endFileWithNavPath(), generateExampleDocs(), writeAlphabeticalExceptionIndex(), writeAlphabeticalIndex(), writeAlphabeticalInterfaceIndex(), writeAlphabeticalStructIndex(), writeAnnotatedIndexGeneric(), writeClassMemberIndexFiltered(), writeConceptIndex(), GroupDefImpl::writeDocumentation(), PageDefImpl::writeDocumentation(), MemberList::writeDocumentationPage(), writeExampleIndex(), writeFileIndex(), writeFileMemberIndexFiltered(), writeGraphicalClassHierarchy(), writeGraphicalExceptionHierarchy(), writeGraphicalInterfaceHierarchy(), writeGraphInfo(), writeGroupIndex(), writeHierarchicalExceptionIndex(), writeHierarchicalIndex(), writeHierarchicalInterfaceIndex(), writeIndex(), ClassDefImpl::writeMemberList(), writeNamespaceIndex(), writeNamespaceMemberIndexFiltered(), writePageIndex(), and writeUserGroupStubPage().
endFileWithNavPath()
void endFileWithNavPath (const Definition * d, OutputList & ol)
Definition at line 321 of file index.cpp.
{
  bool generateTreeView = Config_getBool(GENERATE_TREEVIEW);
  QCString navPath;
  if (generateTreeView)
  {
    ol.pushGeneratorState();
    ol.disableAllBut(OutputType::Html);
    ol.writeString("</div><!-- doc-content -->\n");
    ol.popGeneratorState();
    navPath = d->navigationPathAsString();
  }
  endFile(ol,generateTreeView,TRUE,navPath);
}
References Config_getBool, OutputList::disableAllBut(), endFile(), Html, Definition::navigationPathAsString(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), TRUE, and OutputList::writeString().
Referenced by ConceptDefImpl::writeDocumentation(), DirDefImpl::writeDocumentation(), DirRelation::writeDocumentation(), FileDefImpl::writeDocumentation(), NamespaceDefImpl::writeDocumentation(), PageDefImpl::writeDocumentation(), ClassDefImpl::writeDocumentation(), MemberList::writeDocumentationPage(), and FileDefImpl::writeSourceFooter().
endTitle()
void endTitle (OutputList & ol, const QCString & fileName, const QCString & name)
Definition at line 275 of file index.cpp.
{
  ol.popGeneratorState();
  ol.endTitleHead(fileName,name);
  ol.endHeaderSection();
}
References OutputList::endHeaderSection(), OutputList::endTitleHead(), and OutputList::popGeneratorState().
Referenced by generateExampleDocs(), writeAlphabeticalExceptionIndex(), writeAlphabeticalIndex(), writeAlphabeticalInterfaceIndex(), writeAlphabeticalStructIndex(), writeAnnotatedIndexGeneric(), writeConceptIndex(), ConceptDefImpl::writeDocumentation(), DirDefImpl::writeDocumentation(), FileDefImpl::writeDocumentation(), NamespaceDefImpl::writeDocumentation(), PageDefImpl::writeDocumentation(), ClassDefImpl::writeDocumentation(), writeExampleIndex(), writeFileIndex(), writeGraphicalClassHierarchy(), writeGraphicalExceptionHierarchy(), writeGraphicalInterfaceHierarchy(), writeGraphInfo(), writeGroupIndex(), writeHierarchicalExceptionIndex(), writeHierarchicalIndex(), writeHierarchicalInterfaceIndex(), ClassDefImpl::writeMemberList(), writeNamespaceIndex(), writePageIndex(), FileDefImpl::writeSourceHeader(), and writeUserGroupStubPage().
fixSpaces()
QCString fixSpaces (const QCString & s)
Definition at line 261 of file index.cpp.
{
  return substitute(s," ","&#160;");
}
References substitute().
Referenced by renderQuickLinksAsTabs(), renderQuickLinksAsTree(), writeClassMemberIndexFiltered(), writeFileMemberIndexFiltered(), writeNamespaceMemberIndexFiltered(), and writeUserGroupStubPage().
initClassMemberIndices()
void initClassMemberIndices ()
Definition at line 2702 of file index.cpp.
{
  Index &index = Index::instance();
  int j=0;
  for (j=0;j<ClassMemberHighlight::Total;j++)
  {
    index.resetDocumentedClassMembers(j);
    g_classIndexLetterUsed[j].clear();
  }
}
References g_classIndexLetterUsed, Index::instance(), Index::resetDocumentedClassMembers(), and ClassMemberHighlight::Total.
Referenced by initDoxygen().
initFileMemberIndices()
void initFileMemberIndices ()
Definition at line 2856 of file index.cpp.
{
  Index &index = Index::instance();
  int j=0;
  for (j=0;j<NamespaceMemberHighlight::Total;j++)
  {
    index.resetDocumentedFileMembers(j);
    g_fileIndexLetterUsed[j].clear();
  }
}
References g_fileIndexLetterUsed, Index::instance(), Index::resetDocumentedFileMembers(), and NamespaceMemberHighlight::Total.
Referenced by initDoxygen().
initNamespaceMemberIndices()
void initNamespaceMemberIndices ()
Definition at line 2787 of file index.cpp.
{
  Index &index = Index::instance();
  int j=0;
  for (j=0;j<NamespaceMemberHighlight::Total;j++)
  {
    index.resetDocumentedNamespaceMembers(j);
    g_namespaceIndexLetterUsed[j].clear();
  }
}
References g_namespaceIndexLetterUsed, Index::instance(), Index::resetDocumentedNamespaceMembers(), and NamespaceMemberHighlight::Total.
Referenced by initDoxygen().
sortMemberIndexLists()
void sortMemberIndexLists ()
Definition at line 2943 of file index.cpp.
{
  for (auto &idx : g_classIndexLetterUsed)
  {
    sortMemberIndexList(idx);
  }
  for (auto &idx : g_fileIndexLetterUsed)
  {
    sortMemberIndexList(idx);
  }
  for (auto &idx : g_namespaceIndexLetterUsed)
  {
    sortMemberIndexList(idx);
  }
}
References g_classIndexLetterUsed, g_fileIndexLetterUsed, g_namespaceIndexLetterUsed, and sortMemberIndexList().
Referenced by addMembersToIndex().
startFile()
void startFile (OutputList & ol, const QCString & name, const QCString & manName, const QCString & title, HighlightedItem hli = HighlightedItem::None, bool additionalIndices = FALSE, const QCString & altSidebarName = QCString())
Definition at line 282 of file index.cpp.
{
  bool disableIndex     = Config_getBool(DISABLE_INDEX);
  ol.startFile(name,manName,title);
  ol.startQuickIndices();
  if (!disableIndex)
  {
    ol.writeQuickLinks(TRUE,hli,name);
  }
  if (!additionalIndices)
  {
    ol.endQuickIndices();
  }
  ol.writeSplitBar(!altSidebarName.isEmpty() ? altSidebarName : name);
  ol.writeSearchInfo();
}
References Config_getBool, OutputList::endQuickIndices(), QCString::isEmpty(), OutputList::startFile(), OutputList::startQuickIndices(), TRUE, OutputList::writeQuickLinks(), OutputList::writeSearchInfo(), and OutputList::writeSplitBar().
Referenced by generateExampleDocs(), writeAlphabeticalExceptionIndex(), writeAlphabeticalIndex(), writeAlphabeticalInterfaceIndex(), writeAlphabeticalStructIndex(), writeAnnotatedIndexGeneric(), writeConceptIndex(), ConceptDefImpl::writeDocumentation(), DirDefImpl::writeDocumentation(), DirRelation::writeDocumentation(), FileDefImpl::writeDocumentation(), GroupDefImpl::writeDocumentation(), NamespaceDefImpl::writeDocumentation(), PageDefImpl::writeDocumentation(), ClassDefImpl::writeDocumentation(), MemberList::writeDocumentationPage(), writeExampleIndex(), writeFileIndex(), writeGraphicalClassHierarchy(), writeGraphicalExceptionHierarchy(), writeGraphicalInterfaceHierarchy(), writeGraphInfo(), writeGroupIndex(), writeHierarchicalExceptionIndex(), writeHierarchicalIndex(), writeHierarchicalInterfaceIndex(), writeIndex(), ClassDefImpl::writeMemberList(), writeNamespaceIndex(), writePageIndex(), FileDefImpl::writeSourceHeader(), and writeUserGroupStubPage().
startTitle()
void startTitle (OutputList & ol, const QCString & fileName, const DefinitionMutable * def = 0)
Definition at line 266 of file index.cpp.
{
  ol.startHeaderSection();
  if (def) def->writeSummaryLinks(ol);
  ol.startTitleHead(fileName);
  ol.pushGeneratorState();
  ol.disable(OutputType::Man);
}
References OutputList::disable(), Man, OutputList::pushGeneratorState(), OutputList::startHeaderSection(), OutputList::startTitleHead(), and DefinitionMutable::writeSummaryLinks().
Referenced by generateExampleDocs(), writeAlphabeticalExceptionIndex(), writeAlphabeticalIndex(), writeAlphabeticalInterfaceIndex(), writeAlphabeticalStructIndex(), writeAnnotatedIndexGeneric(), writeConceptIndex(), ConceptDefImpl::writeDocumentation(), DirDefImpl::writeDocumentation(), FileDefImpl::writeDocumentation(), NamespaceDefImpl::writeDocumentation(), PageDefImpl::writeDocumentation(), ClassDefImpl::writeDocumentation(), writeExampleIndex(), writeFileIndex(), writeGraphicalClassHierarchy(), writeGraphicalExceptionHierarchy(), writeGraphicalInterfaceHierarchy(), writeGraphInfo(), writeGroupIndex(), writeHierarchicalExceptionIndex(), writeHierarchicalIndex(), writeHierarchicalInterfaceIndex(), ClassDefImpl::writeMemberList(), writeNamespaceIndex(), writePageIndex(), FileDefImpl::writeSourceHeader(), and writeUserGroupStubPage().
writeGraphInfo()
void writeGraphInfo (OutputList & ol)
Definition at line 3746 of file index.cpp.
{
  if (!Config_getBool(HAVE_DOT) || !Config_getBool(GENERATE_HTML)) return;
  ol.pushGeneratorState();
  ol.disableAllBut(OutputType::Html);
  DotLegendGraph gd;
  gd.writeGraph(Config_getString(HTML_OUTPUT));
  bool oldStripCommentsState = Config_getBool(STRIP_CODE_COMMENTS);
  bool oldCreateSubdirs = Config_getBool(CREATE_SUBDIRS);
  // temporarily disable the stripping of comments for our own code example!
  Config_updateBool(STRIP_CODE_COMMENTS,FALSE);
  // temporarily disable create subdirs for linking to our example
  Config_updateBool(CREATE_SUBDIRS,FALSE);
  startFile(ol,"graph_legend",QCString(),theTranslator->trLegendTitle());
  startTitle(ol,QCString());
  ol.parseText(theTranslator->trLegendTitle());
  endTitle(ol,QCString(),QCString());
  ol.startContents();
  QCString legendDocs = theTranslator->trLegendDocs();
  int s = legendDocs.find("<center>");
  int e = legendDocs.find("</center>");
  QCString imgExt = getDotImageExtension();
  if (imgExt=="svg" && s!=-1 && e!=-1)
  {
    legendDocs = legendDocs.left(s+8) + "
\n" + legendDocs.mid(e);
    //printf("legendDocs=%s\n",qPrint(legendDocs));
  }
  FileDef *fd = createFileDef("","graph_legend.dox");
  ol.generateDoc("graph_legend",1,fd,0,legendDocs,FALSE,FALSE,
                 QCString(),FALSE,FALSE,FALSE);
  delete fd;
  // restore config settings
  Config_updateBool(STRIP_CODE_COMMENTS,oldStripCommentsState);
  Config_updateBool(CREATE_SUBDIRS,oldCreateSubdirs);
  endFile(ol);
  ol.popGeneratorState();
}
References Config_getBool, Config_getString, Config_updateBool, createFileDef(), OutputList::disableAllBut(), endFile(), endTitle(), FALSE, QCString::find(), OutputList::generateDoc(), getDotImageExtension(), Html, QCString::left(), QCString::mid(), OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputList::startContents(), startFile(), startTitle(), theTranslator, Translator::trLegendDocs(), Translator::trLegendTitle(), and DotLegendGraph::writeGraph().
Referenced by generateOutput().
writeIndexHierarchy()
void writeIndexHierarchy (OutputList & ol)
Definition at line 5249 of file index.cpp.
{
  writeMenuData();
  LayoutNavEntry *lne = LayoutDocManager::instance().rootNavEntry();
  if (lne)
  {
    writeIndexHierarchyEntries(ol,lne->children());
  }
}
References LayoutNavEntry::children(), LayoutDocManager::instance(), LayoutDocManager::rootNavEntry(), writeIndexHierarchyEntries(), and writeMenuData().
Referenced by generateOutput().