Doxygen: src/symbolresolver.cpp File Reference
symbolresolver.cpp File Reference
#include <unordered_map>
#include <string>
#include <vector>
#include "symbolresolver.h"
#include "util.h"
#include "doxygen.h"
#include "namespacedef.h"
#include "config.h"
#include "defargs.h"
Classes
class AccessStack
Helper class representing the stack of items considered while resolving the scope.
struct AccessStack::AccessElem
Element in the stack.
struct SymbolResolver::Private
Typedefs
using VisitedNamespaces = std::unordered_map< std::string, const Definition * >
Functions
static bool isParentScope (const Definition *parent, const Definition *item)
Variables
static std::mutex g_cacheMutex
static std::recursive_mutex g_cacheTypedefMutex
Typedef Documentation
VisitedNamespaces
using VisitedNamespaces = std::unordered_map<std::string,const Definition *>
Definition at line 83 of file symbolresolver.cpp.
Function Documentation
isParentScope()
static bool isParentScope (const Definition * parent, const Definition * item) static
Definition at line 929 of file symbolresolver.cpp.
{
  if (parent==item || item==0 || item==Doxygen::globalScope) return false;
  if (parent==0 || parent==Doxygen::globalScope)             return true;
  return isParentScope(parent->getOuterScope(),item);
}
References Doxygen::globalScope, isParentScope(), and parent().
Referenced by SymbolResolver::Private::isAccessibleFromWithExpScope(), and isParentScope().
Variable Documentation
g_cacheMutex
std::mutex g_cacheMutex static
Definition at line 27 of file symbolresolver.cpp.
Referenced by SymbolResolver::Private::getResolvedSymbolRec(), and SymbolResolver::Private::getResolvedTypeRec().
g_cacheTypedefMutex
std::recursive_mutex g_cacheTypedefMutex static
Definition at line 28 of file symbolresolver.cpp.
Referenced by SymbolResolver::Private::newResolveTypedef().