Doxygen: Index Class Reference
Index Class Reference
#include <index.h>
Classes
struct Private
Public Member Functions
void countDataStructures ()
int numAnnotatedClasses () const
int numAnnotatedClassesPrinted () const
int numHierarchyClasses () const
int numAnnotatedInterfaces () const
int numAnnotatedInterfacesPrinted () const
int numHierarchyInterfaces () const
int numAnnotatedStructs () const
int numAnnotatedStructsPrinted () const
int numAnnotatedExceptions () const
int numAnnotatedExceptionsPrinted () const
int numHierarchyExceptions () const
int numDocumentedGroups () const
int numDocumentedNamespaces () const
int numDocumentedConcepts () const
int numIndexedPages () const
int numDocumentedFiles () const
int numDocumentedPages () const
int numDocumentedDirs () const
int numDocumentedClassMembers (ClassMemberHighlight::Enum e) const
int numDocumentedFileMembers (FileMemberHighlight::Enum e) const
int numDocumentedNamespaceMembers (NamespaceMemberHighlight::Enum e) const
void resetDocumentedClassMembers (int i)
void resetDocumentedFileMembers (int i)
void resetDocumentedNamespaceMembers (int i)
void incrementDocumentedClassMembers (int i)
void incrementDocumentedFileMembers (int i)
void incrementDocumentedNamespaceMembers (int i)
Static Public Member Functions
static Index & instance ()
Private Member Functions
Index ()
~Index ()
Private Attributes
std::unique_ptr< Private > p
Detailed Description
Definition at line 142 of file index.h.
Constructor & Destructor Documentation
Index()
Index::Index () private
Definition at line 91 of file index.cpp.
             : p(std::make_unique<Private>())
{
}
~Index()
Index::~Index () private default
Member Function Documentation
countDataStructures()
void Index::countDataStructures ()
Definition at line 133 of file index.cpp.
{
  bool sliceOpt = Config_getBool(OPTIMIZE_OUTPUT_SLICE);
  p->annotatedClasses           = countAnnotatedClasses(&p->annotatedClassesPrinted, ClassDef::Class); // "classes" + "annotated"
  p->hierarchyClasses           = countClassHierarchy(ClassDef::Class);     // "hierarchy"
  // "interfaces" + "annotated"
  p->annotatedInterfaces        = sliceOpt ? countAnnotatedClasses(&p->annotatedInterfacesPrinted, ClassDef::Interface) : 0;
  // "interfacehierarchy"
  p->hierarchyInterfaces        = sliceOpt ? countClassHierarchy(ClassDef::Interface) : 0;
  // "structs" + "annotated"
  p->annotatedStructs           = sliceOpt ? countAnnotatedClasses(&p->annotatedStructsPrinted, ClassDef::Struct) : 0;
  // "exceptions" + "annotated"
  p->annotatedExceptions        = sliceOpt ? countAnnotatedClasses(&p->annotatedExceptionsPrinted, ClassDef::Exception) : 0;
  // "exceptionhierarchy"
  p->hierarchyExceptions        = sliceOpt ? countClassHierarchy(ClassDef::Exception) : 0;
  countFiles(p->documentedFiles,p->documentedFiles);         // "files"
  countRelatedPages(p->documentedPages,p->indexedPages);     // "pages"
  p->documentedGroups           = countGroups();             // "modules"
  p->documentedNamespaces       = countNamespaces();         // "namespaces"
  p->documentedConcepts         = countConcepts();           // "concepts"
  p->documentedDirs             = countDirs();               // "dirs"
  // "globals"
  // "namespacemembers"
  // "functions"
}
References ClassDef::Class, Config_getBool, countAnnotatedClasses(), countClassHierarchy(), countConcepts(), countDirs(), countFiles(), countGroups(), countNamespaces(), countRelatedPages(), ClassDef::Exception, ClassDef::Interface, p, and ClassDef::Struct.
Referenced by parseInput().
incrementDocumentedClassMembers()
void Index::incrementDocumentedClassMembers (int i)
Definition at line 127 of file index.cpp.
{ p->documentedClassMembers[i]++;     }
References p.
Referenced by addClassMemberNameToIndex().
incrementDocumentedFileMembers()
void Index::incrementDocumentedFileMembers (int i)
Definition at line 128 of file index.cpp.
{ p->documentedFileMembers[i]++;      }
References p.
Referenced by addFileMemberNameToIndex().
incrementDocumentedNamespaceMembers()
void Index::incrementDocumentedNamespaceMembers (int i)
Definition at line 129 of file index.cpp.
{ p->documentedNamespaceMembers[i]++; }
References p.
Referenced by addNamespaceMemberNameToIndex().
instance()
Index & Index::instance () static
Definition at line 97 of file index.cpp.
{
  static Index index;
  return index;
}
Referenced by addClassMemberNameToIndex(), addFileMemberNameToIndex(), addNamespaceMemberNameToIndex(), generateFileDocs(), generatePageDocs(), initClassMemberIndices(), initFileMemberIndices(), initNamespaceMemberIndices(), parseInput(), quickLinkVisible(), renderQuickLinksAsJs(), writeAlphabeticalExceptionIndex(), writeAlphabeticalIndex(), writeAlphabeticalInterfaceIndex(), writeAlphabeticalStructIndex(), writeAnnotatedExceptionIndex(), writeAnnotatedIndex(), writeAnnotatedInterfaceIndex(), writeAnnotatedStructIndex(), writeClassMemberIndex(), writeClassMemberIndexFiltered(), writeConceptIndex(), writeFileIndex(), writeFileMemberIndex(), writeFileMemberIndexFiltered(), writeGraphicalClassHierarchy(), writeGraphicalExceptionHierarchy(), writeGraphicalInterfaceHierarchy(), writeGroupIndex(), writeHierarchicalExceptionIndex(), writeHierarchicalIndex(), writeHierarchicalInterfaceIndex(), writeIndex(), writeIndexHierarchyEntries(), writeNamespaceIndex(), writeNamespaceMemberIndex(), writeNamespaceMemberIndexFiltered(), and writePageIndex().
numAnnotatedClasses()
int Index::numAnnotatedClasses () const
Definition at line 103 of file index.cpp.
{ return p->annotatedClasses;        }
References p.
numAnnotatedClassesPrinted()
int Index::numAnnotatedClassesPrinted () const
Definition at line 104 of file index.cpp.
{ return p->annotatedClassesPrinted; }
References p.
numAnnotatedExceptions()
int Index::numAnnotatedExceptions () const
Definition at line 111 of file index.cpp.
{ return p->annotatedExceptions; }
References p.
numAnnotatedExceptionsPrinted()
int Index::numAnnotatedExceptionsPrinted () const
Definition at line 112 of file index.cpp.
{ return p->annotatedExceptionsPrinted; }
References p.
numAnnotatedInterfaces()
int Index::numAnnotatedInterfaces () const
Definition at line 106 of file index.cpp.
{ return p->annotatedInterfaces; }
References p.
numAnnotatedInterfacesPrinted()
int Index::numAnnotatedInterfacesPrinted () const
Definition at line 107 of file index.cpp.
{ return p->annotatedInterfacesPrinted; }
References p.
numAnnotatedStructs()
int Index::numAnnotatedStructs () const
Definition at line 109 of file index.cpp.
{ return p->annotatedStructs; }
References p.
numAnnotatedStructsPrinted()
int Index::numAnnotatedStructsPrinted () const
Definition at line 110 of file index.cpp.
{ return p->annotatedStructsPrinted; }
References p.
numDocumentedClassMembers()
int Index::numDocumentedClassMembers (ClassMemberHighlight::Enum e) const
Definition at line 121 of file index.cpp.
{ return p->documentedClassMembers[e]; }
References p.
Referenced by renderQuickLinksAsJs().
numDocumentedConcepts()
int Index::numDocumentedConcepts () const
Definition at line 116 of file index.cpp.
{ return p->documentedConcepts; }
References p.
numDocumentedDirs()
int Index::numDocumentedDirs () const
Definition at line 120 of file index.cpp.
{ return p->documentedDirs; }
References p.
numDocumentedFileMembers()
int Index::numDocumentedFileMembers (FileMemberHighlight::Enum e) const
Definition at line 122 of file index.cpp.
{ return p->documentedFileMembers[e];  }
References p.
Referenced by renderQuickLinksAsJs(), and writeFileMemberIndexFiltered().
numDocumentedFiles()
int Index::numDocumentedFiles () const
Definition at line 118 of file index.cpp.
{ return p->documentedFiles; }
References p.
numDocumentedGroups()
int Index::numDocumentedGroups () const
Definition at line 114 of file index.cpp.
{ return p->documentedGroups; }
References p.
numDocumentedNamespaceMembers()
int Index::numDocumentedNamespaceMembers (NamespaceMemberHighlight::Enum e) const
Definition at line 123 of file index.cpp.
{ return p->documentedNamespaceMembers[e]; }
References p.
Referenced by renderQuickLinksAsJs().
numDocumentedNamespaces()
int Index::numDocumentedNamespaces () const
Definition at line 115 of file index.cpp.
{ return p->documentedNamespaces; }
References p.
numDocumentedPages()
int Index::numDocumentedPages () const
Definition at line 119 of file index.cpp.
{ return p->documentedPages; }
References p.
numHierarchyClasses()
int Index::numHierarchyClasses () const
Definition at line 105 of file index.cpp.
{ return p->hierarchyClasses;        }
References p.
numHierarchyExceptions()
int Index::numHierarchyExceptions () const
Definition at line 113 of file index.cpp.
{ return p->hierarchyExceptions; }
References p.
numHierarchyInterfaces()
int Index::numHierarchyInterfaces () const
Definition at line 108 of file index.cpp.
{ return p->hierarchyInterfaces; }
References p.
numIndexedPages()
int Index::numIndexedPages () const
Definition at line 117 of file index.cpp.
{ return p->indexedPages; }
References p.
resetDocumentedClassMembers()
void Index::resetDocumentedClassMembers (int i)
Definition at line 124 of file index.cpp.
{ p->documentedClassMembers[i]    =0; }
References p.
Referenced by initClassMemberIndices().
resetDocumentedFileMembers()
void Index::resetDocumentedFileMembers (int i)
Definition at line 125 of file index.cpp.
{ p->documentedFileMembers[i]     =0; }
References p.
Referenced by initFileMemberIndices().
resetDocumentedNamespaceMembers()
void Index::resetDocumentedNamespaceMembers (int i)
Definition at line 126 of file index.cpp.
{ p->documentedNamespaceMembers[i]=0; }
References p.
Referenced by initNamespaceMemberIndices().
Member Data Documentation
p
std::unique_ptr<Private> Index::p private
Definition at line 178 of file index.h.
Referenced by countDataStructures(), incrementDocumentedClassMembers(), incrementDocumentedFileMembers(), incrementDocumentedNamespaceMembers(), numAnnotatedClasses(), numAnnotatedClassesPrinted(), numAnnotatedExceptions(), numAnnotatedExceptionsPrinted(), numAnnotatedInterfaces(), numAnnotatedInterfacesPrinted(), numAnnotatedStructs(), numAnnotatedStructsPrinted(), numDocumentedClassMembers(), numDocumentedConcepts(), numDocumentedDirs(), numDocumentedFileMembers(), numDocumentedFiles(), numDocumentedGroups(), numDocumentedNamespaceMembers(), numDocumentedNamespaces(), numDocumentedPages(), numHierarchyClasses(), numHierarchyExceptions(), numHierarchyInterfaces(), numIndexedPages(), resetDocumentedClassMembers(), resetDocumentedFileMembers(), and resetDocumentedNamespaceMembers().
The documentation for this class was generated from the following files:
/home/runner/work/doxygen/doxygen/src/index.h
/home/runner/work/doxygen/doxygen/src/index.cpp